# Generated by Django 6.0.6 on 2026-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("placed", "Placed"), ("cancelled", "Cancelled")],
                default="placed",
                max_length=20,
            ),
        ),
    ]
