# Generated by Django 6.0.6 on 2026-06-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(default="placed", max_length=20),
        ),
    ]
