# Generated by Django 6.0.6 on 2026-06-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_order_status_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("placed", "Placed"), ("cancelled", "Cancelled")],
                default="placed",
                max_length=20,
            ),
        ),
    ]
